package BatalhaPokemons.Pokemon

import BatalhaPokemons.Enums.TiposPokemon

class Pokemon(
    var nome: String, tipo: List<TiposPokemon>, val fraquezas: List<TiposPokemon>
) {

    val tipo: List<TiposPokemon>
        get() {
            TODO()
        }

    companion object {
        val todosPokemons: Map<String, Pokemon>
            get() = listOf(
                Pokemon("Bulbasaur", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.GELO, TiposPokemon.PSIQUICO)),
                Pokemon("Ivysaur", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.GELO, TiposPokemon.PSIQUICO)),
                Pokemon("Venusaur", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.GELO, TiposPokemon.PSIQUICO)),
                Pokemon("Charmander", mutableListOf(TiposPokemon.FOGO), mutableListOf(TiposPokemon.AGUA, TiposPokemon.TERRA, TiposPokemon.PEDRA)),
                Pokemon("Charmeleon", mutableListOf(TiposPokemon.FOGO), mutableListOf(TiposPokemon.AGUA, TiposPokemon.TERRA, TiposPokemon.PEDRA)),
                Pokemon("Charizard", mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.AGUA, TiposPokemon.ELETRICO, TiposPokemon.PEDRA)),
                Pokemon("Squirtle", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Wartortle", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Blastoise", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Caterpie", mutableListOf(TiposPokemon.INSETO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Metapod", mutableListOf(TiposPokemon.INSETO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Butterfree", mutableListOf(TiposPokemon.INSETO, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Weedle", mutableListOf(TiposPokemon.INSETO, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Kakuna", mutableListOf(TiposPokemon.INSETO, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Beedrill", mutableListOf(TiposPokemon.INSETO, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Pidgey", mutableListOf(TiposPokemon.NORMAL, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.PEDRA)),
                Pokemon("Pidgeotto", mutableListOf(TiposPokemon.NORMAL, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.PEDRA)),
                Pokemon("Pidgeot", mutableListOf(TiposPokemon.NORMAL, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.PEDRA)),
                Pokemon("Rattata", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Raticate", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Spearow", mutableListOf(TiposPokemon.NORMAL, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.PEDRA)),
                Pokemon("Fearow", mutableListOf(TiposPokemon.NORMAL, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.PEDRA)),
                Pokemon("Ekans", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Arbok", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Pikachu", mutableListOf(TiposPokemon.ELETRICO), mutableListOf(TiposPokemon.AGUA, TiposPokemon.VOADOR)),
                Pokemon("Raichu", mutableListOf(TiposPokemon.ELETRICO), mutableListOf(TiposPokemon.AGUA, TiposPokemon.VOADOR)),
                Pokemon("Sandshrew", mutableListOf(TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO, TiposPokemon.PLANTA)),
                Pokemon("Sandslash", mutableListOf(TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO, TiposPokemon.PLANTA)),
                Pokemon("Nidoran♀", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Nidorina", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Nidoqueen", mutableListOf(TiposPokemon.VENENOSO, TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO, TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Nidoran♂", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Nidorino", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Nidoking", mutableListOf(TiposPokemon.VENENOSO, TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO, TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Clefairy", mutableListOf(TiposPokemon.FADA), mutableListOf(TiposPokemon.VENENOSO, TiposPokemon.FANTASMA, TiposPokemon.METALICO)),
                Pokemon("Clefable", mutableListOf(TiposPokemon.FADA), mutableListOf(TiposPokemon.VENENOSO, TiposPokemon.FANTASMA, TiposPokemon.METALICO)),
                Pokemon("Zubat", mutableListOf(TiposPokemon.VENENOSO, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Golbat", mutableListOf(TiposPokemon.VENENOSO, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Oddish", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.GELO, TiposPokemon.PSIQUICO)),
                Pokemon("Gloom", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.GELO, TiposPokemon.PSIQUICO)),
                Pokemon("Vileplume", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.GELO, TiposPokemon.PSIQUICO)),
                Pokemon("Paras", mutableListOf(TiposPokemon.INSETO, TiposPokemon.PLANTA), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Parasect", mutableListOf(TiposPokemon.INSETO, TiposPokemon.PLANTA), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Venonat", mutableListOf(TiposPokemon.INSETO, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Venomoth", mutableListOf(TiposPokemon.INSETO, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PSIQUICO)),
                Pokemon("Diglett", mutableListOf(TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO, TiposPokemon.PLANTA)),
                Pokemon("Dugtrio", mutableListOf(TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO, TiposPokemon.PLANTA)),
                Pokemon("Meowth", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Persian", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Psyduck", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Golduck", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Mankey", mutableListOf(TiposPokemon.LUTA), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.VOADOR)),
                Pokemon("Primeape", mutableListOf(TiposPokemon.LUTA), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.VOADOR)),
                Pokemon("Poliwag", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Poliwhirl", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Politoed", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Abra", mutableListOf(TiposPokemon.PSIQUICO), mutableListOf(TiposPokemon.FANTASMA, TiposPokemon.SOMBRIO)),
                Pokemon("Kadabra", mutableListOf(TiposPokemon.PSIQUICO), mutableListOf(TiposPokemon.FANTASMA, TiposPokemon.SOMBRIO)),
                Pokemon("Alakazam", mutableListOf(TiposPokemon.PSIQUICO), mutableListOf(TiposPokemon.FANTASMA, TiposPokemon.SOMBRIO)),
                Pokemon("Machop", mutableListOf(TiposPokemon.LUTA), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.VOADOR)),
                Pokemon("Machoke", mutableListOf(TiposPokemon.LUTA), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.VOADOR)),
                Pokemon("Machamp", mutableListOf(TiposPokemon.LUTA), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.VOADOR)),
                Pokemon("Bellsprout", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.GELO, TiposPokemon.PSIQUICO)),
                Pokemon("Weepinbell", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.GELO, TiposPokemon.PSIQUICO)),
                Pokemon("Victreebel", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.GELO, TiposPokemon.PSIQUICO)),
                Pokemon("Tentacool", mutableListOf(TiposPokemon.AGUA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Tentacruel", mutableListOf(TiposPokemon.AGUA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Geodude", mutableListOf(TiposPokemon.PEDRA, TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO, TiposPokemon.PLANTA, TiposPokemon.LUTA, TiposPokemon.VOADOR)),
                Pokemon("Graveler", mutableListOf(TiposPokemon.PEDRA, TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO, TiposPokemon.PLANTA, TiposPokemon.LUTA, TiposPokemon.VOADOR)),
                Pokemon("Golem", mutableListOf(TiposPokemon.PEDRA, TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO, TiposPokemon.PLANTA, TiposPokemon.LUTA, TiposPokemon.VOADOR)),
                Pokemon("Ponyta", mutableListOf(TiposPokemon.FOGO), mutableListOf(TiposPokemon.AGUA, TiposPokemon.TERRA, TiposPokemon.PEDRA)),
                Pokemon("Rapidash", mutableListOf(TiposPokemon.FOGO), mutableListOf(TiposPokemon.AGUA, TiposPokemon.TERRA, TiposPokemon.PEDRA)),
                Pokemon("Magnemite", mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.METALICO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.LUTA, TiposPokemon.TERRA)),
                Pokemon("Magneton", mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.METALICO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.LUTA, TiposPokemon.TERRA)),
                Pokemon("Farfetch'd", mutableListOf(TiposPokemon.NORMAL, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.PEDRA)),
                Pokemon("Doduo", mutableListOf(TiposPokemon.NORMAL, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.PEDRA)),
                Pokemon("Dodrio", mutableListOf(TiposPokemon.NORMAL, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.PEDRA)),
                Pokemon("Seel", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Dewgong", mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Grimer", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Muk", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)) ,
                Pokemon("Shellder", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Cloyster", mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA, TiposPokemon.LUTA)),
                Pokemon("Gastly", mutableListOf(TiposPokemon.FANTASMA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.FANTASMA)),
                Pokemon("Haunter", mutableListOf(TiposPokemon.FANTASMA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.FANTASMA)),
                Pokemon("Gengar", mutableListOf(TiposPokemon.FANTASMA, TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.FANTASMA)),
                Pokemon("Onix", mutableListOf(TiposPokemon.PEDRA, TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.PLANTA, TiposPokemon.GELO, TiposPokemon.LUTA, TiposPokemon.TERRA)),
                Pokemon("Drowzee", mutableListOf(TiposPokemon.PSIQUICO), mutableListOf(TiposPokemon.FANTASMA, TiposPokemon.SOMBRIO, TiposPokemon.INSETO)),
                Pokemon("Hypno", mutableListOf(TiposPokemon.PSIQUICO), mutableListOf(TiposPokemon.FANTASMA, TiposPokemon.SOMBRIO, TiposPokemon.INSETO)),
                Pokemon("Krabby", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Kingler", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Voltorb", mutableListOf(TiposPokemon.ELETRICO), mutableListOf(TiposPokemon.TERRA)),
                Pokemon("Electrode", mutableListOf(TiposPokemon.ELETRICO), mutableListOf(TiposPokemon.TERRA)),
                Pokemon("Exeggcute", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.PSIQUICO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.GELO, TiposPokemon.VENENOSO, TiposPokemon.VOADOR, TiposPokemon.INSETO, TiposPokemon.SOMBRIO)),
                Pokemon("Exeggutor", mutableListOf(TiposPokemon.PLANTA, TiposPokemon.PSIQUICO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.GELO, TiposPokemon.VENENOSO, TiposPokemon.VOADOR, TiposPokemon.INSETO, TiposPokemon.SOMBRIO)),
                Pokemon("Cubone", mutableListOf(TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.PLANTA, TiposPokemon.GELO)),
                Pokemon("Marowak", mutableListOf(TiposPokemon.TERRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.PLANTA, TiposPokemon.GELO)),
                Pokemon("Hitmonlee", mutableListOf(TiposPokemon.LUTA), mutableListOf(TiposPokemon.VOADOR, TiposPokemon.PSIQUICO, TiposPokemon.FADA)),
                Pokemon("Hitmonchan", mutableListOf(TiposPokemon.LUTA), mutableListOf(TiposPokemon.VOADOR, TiposPokemon.PSIQUICO, TiposPokemon.FADA)),
                Pokemon("Lickitung", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Koffing", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Weezing", mutableListOf(TiposPokemon.VENENOSO), mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.TERRA)),
                Pokemon("Rhyhorn", mutableListOf(TiposPokemon.TERRA, TiposPokemon.PEDRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.PLANTA, TiposPokemon.GELO, TiposPokemon.LUTA, TiposPokemon.METALICO)),
                Pokemon("Rhydon", mutableListOf(TiposPokemon.TERRA, TiposPokemon.PEDRA), mutableListOf(TiposPokemon.AGUA, TiposPokemon.PLANTA, TiposPokemon.GELO, TiposPokemon.LUTA, TiposPokemon.METALICO)),
                Pokemon("Chansey", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Tangela", mutableListOf(TiposPokemon.PLANTA), mutableListOf(TiposPokemon.FOGO, TiposPokemon.GELO, TiposPokemon.VOADOR, TiposPokemon.VENENOSO, TiposPokemon.INSETO)),
                Pokemon("Kangaskhan", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Horsea", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Seadra", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Goldeen", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Seaking", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Staryu", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Starmie", mutableListOf(TiposPokemon.AGUA, TiposPokemon.PSIQUICO), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA, TiposPokemon.FANTASMA, TiposPokemon.SOMBRIO, TiposPokemon.INSETO)),
                Pokemon("Mr. Mime", mutableListOf(TiposPokemon.PSIQUICO, TiposPokemon.FADA), mutableListOf(TiposPokemon.FANTASMA, TiposPokemon.SOMBRIO, TiposPokemon.METALICO)),
                Pokemon("Scyther", mutableListOf(TiposPokemon.INSETO, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.FOGO, TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.VOADOR, TiposPokemon.PEDRA)),
                Pokemon("Jynx", mutableListOf(TiposPokemon.GELO, TiposPokemon.PSIQUICO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.FANTASMA, TiposPokemon.SOMBRIO, TiposPokemon.METALICO, TiposPokemon.INSETO)),
                Pokemon("Electabuzz", mutableListOf(TiposPokemon.ELETRICO), mutableListOf(TiposPokemon.TERRA)),
                Pokemon("Magmar", mutableListOf(TiposPokemon.FOGO), mutableListOf(TiposPokemon.AGUA, TiposPokemon.TERRA, TiposPokemon.PEDRA)),
                Pokemon("Pinsir", mutableListOf(TiposPokemon.INSETO), mutableListOf(TiposPokemon.FOGO, TiposPokemon.VOADOR, TiposPokemon.PEDRA)),
                Pokemon("Tauros", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Magikarp", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Gyarados", mutableListOf(TiposPokemon.AGUA, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PEDRA)),
                Pokemon("Lapras", mutableListOf(TiposPokemon.AGUA, TiposPokemon.GELO), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA, TiposPokemon.LUTA, TiposPokemon.PEDRA)),
                Pokemon("Ditto", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Eevee", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Vaporeon", mutableListOf(TiposPokemon.AGUA), mutableListOf(TiposPokemon.ELETRICO, TiposPokemon.PLANTA)),
                Pokemon("Jolteon", mutableListOf(TiposPokemon.ELETRICO), mutableListOf(TiposPokemon.TERRA)),
                Pokemon("Flareon", mutableListOf(TiposPokemon.FOGO), mutableListOf(TiposPokemon.AGUA, TiposPokemon.TERRA, TiposPokemon.PEDRA)),
                Pokemon("Porygon", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Omanyte", mutableListOf(TiposPokemon.PEDRA, TiposPokemon.AGUA), mutableListOf(TiposPokemon.PLANTA, TiposPokemon.ELETRICO, TiposPokemon.LUTA, TiposPokemon.TERRA)),
                Pokemon("Omastar", mutableListOf(TiposPokemon.PEDRA, TiposPokemon.AGUA), mutableListOf(TiposPokemon.PLANTA, TiposPokemon.ELETRICO, TiposPokemon.LUTA, TiposPokemon.TERRA)),
                Pokemon("Kabuto", mutableListOf(TiposPokemon.PEDRA, TiposPokemon.AGUA), mutableListOf(TiposPokemon.PLANTA, TiposPokemon.ELETRICO, TiposPokemon.LUTA, TiposPokemon.TERRA)),
                Pokemon("Kabutops", mutableListOf(TiposPokemon.PEDRA, TiposPokemon.AGUA), mutableListOf(TiposPokemon.PLANTA, TiposPokemon.ELETRICO, TiposPokemon.LUTA, TiposPokemon.TERRA)),
                Pokemon("Aerodactyl", mutableListOf(TiposPokemon.PEDRA, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.AGUA, TiposPokemon.ELETRICO, TiposPokemon.GELO, TiposPokemon.PEDRA, TiposPokemon.METALICO)),
                Pokemon("Snorlax", mutableListOf(TiposPokemon.NORMAL), mutableListOf(TiposPokemon.LUTA)),
                Pokemon("Articuno", mutableListOf(TiposPokemon.GELO, TiposPokemon.VOADOR), mutableListOf(TiposPokemon.PEDRA, TiposPokemon.FOGO, TiposPokemon.ELETRICO, TiposPokemon.METALICO))


            ).associateBy { it.nome }
    }
}
